=== finnor-archive/base/Java/AI for Space Racer/spaceracer/RaceSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- Definition of simple types -->

<xs:simpleType name="modelType">
    <xs:restriction base="xs:string">
        <xs:pattern value="([a-zA-Z0-9_ \-])*[.][j][m][e]"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="aiType">
    <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z]([a-zA-Z0-9_ ])*[.][c][l][a][s][s]"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="amountType">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="1000"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="speedType">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="100.0"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="xType">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="3000.0"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="yType">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="-512.0"/>
        <xs:maxInclusive value="512.0"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="nameType">
    <xs:restriction base="xs:string"/>
</xs:simpleType>

<xs:simpleType name="widthType">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="8"/>
        <xs:maxInclusive value="3000"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="heightType">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="8"/>
        <xs:maxInclusive value="1024"/>
    </xs:restriction>
</xs:simpleType>

<!-- Definition of complex types -->

<xs:complexType name="attrxymodel">
    <xs:attribute name="x" type="xType" use="required"/>
    <xs:attribute name="y" type="yType" use="required"/>
    <xs:attribute name="model" type="modelType" use="optional"/>
</xs:complexType>

<xs:complexType name="attrxLeftxRightamountmodel">
    <xs:attribute name="xLeft" type="xType" use="required"/>
    <xs:attribute name="xRight" type="xType" use="required"/>
    <xs:attribute name="amount" type="amountType" use="required"/>
    <xs:attribute name="model" type="modelType" use="optional"/>
</xs:complexType>

<xs:complexType name="attrxmodel">
    <xs:attribute name="x" type="xType" use="required"/>
    <xs:attribute name="model" type="modelType" use="optional"/>
</xs:complexType>

<xs:complexType name="attrnamexymodelai">
    <xs:attribute name="name" type="nameType" use="required"/>
    <xs:attribute name="x" type="xType" use="required"/>
    <xs:attribute name="y" type="yType" use="required"/>
     <xs:attribute name="model" type="modelType" use="required"/>
    <xs:attribute name="ai" type="aiType" use="required"/>
</xs:complexType>

<xs:complexType name="attrnamewidthheight">
    <xs:attribute name="name" type="nameType" use="required"/>
    <xs:attribute name="width" type="widthType" use="required"/>
    <xs:attribute name="height" type="heightType" use="required"/>
</xs:complexType>

<xs:complexType name="attrobjectamountxLeftxRightmodel">
	<xs:attribute name="object" type="xs:string" use="required" />
	<xs:attribute name="amount" type="amountType" use="required" />
	<xs:attribute name="xLeft" type="xType" use="required" />
	<xs:attribute name="xRight" type="xType" use="required" />
	<xs:attribute name="model" type="modelType" use="optional" />
</xs:complexType>

<xs:complexType name="attrobjectxmodel">
	<xs:attribute name="object" type="xs:string" use="required" />
	<xs:attribute name="x" type="xType" use="required" />
	<xs:attribute name="model" type="modelType" use="optional" />
</xs:complexType>

<!-- Definition of a full race -->

<xs:element name="race">
    <xs:complexType>
	    <xs:complexContent>
		    <xs:extension base="attrnamewidthheight">
			    <xs:sequence>
			        <xs:element maxOccurs="unbounded" minOccurs="0" name="asteroid" type="attrxymodel"/>
			        <xs:element maxOccurs="unbounded" minOccurs="0" name="comet">
			            <xs:complexType>
			            	<xs:complexContent>
			            		<xs:extension base="attrxymodel">
			            			<xs:attribute name="speed" type="speedType" use="required"/>
			            		</xs:extension>
			            	</xs:complexContent>			                
			            </xs:complexType>
			        </xs:element>
			        <xs:element maxOccurs="unbounded" minOccurs="0" name="powerUp" type="attrxymodel"/>
			        <xs:element maxOccurs="unbounded" minOccurs="0" name="randomized" type="attrobjectamountxLeftxRightmodel" />
			        <xs:element maxOccurs="unbounded" minOccurs="0" name="wall" type="attrobjectxmodel"/>
			        <xs:element maxOccurs="unbounded" minOccurs="0" name="spaceship" type="attrnamexymodelai"/>
			    </xs:sequence>
		    </xs:extension>
	    </xs:complexContent>
    </xs:complexType>
</xs:element>

</xs:schema>

=== finnor-archive/base/Java/AI for Space Racer/spaceracer/races/Question3_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<race name="Day 4 Exercise 2" width="1000" height="32" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RaceSchema.xsd">
	<asteroid x="228.96455" y="-4.7280045" model="asteroid.jme" />
	<asteroid x="290.54602" y="10.1509495" model="asteroid.jme" />
	<asteroid x="192.16953" y="-15.578088" model="asteroid.jme" />
	<asteroid x="136.20007" y="-1.6384792" model="asteroid.jme" />
	<asteroid x="243.54106" y="-11.775345" model="asteroid.jme" />
	<asteroid x="290.73956" y="-8.278977" model="asteroid.jme" />
	<asteroid x="350.33783" y="15.286282" model="asteroid.jme" />
	<asteroid x="131.9508" y="-3.9017544" model="asteroid.jme" />
	<asteroid x="148.44626" y="-1.160327" model="asteroid.jme" />
	<asteroid x="206.51553" y="13.043182" model="asteroid.jme" />
	<asteroid x="169.92795" y="-14.497529" model="asteroid.jme" />
	<asteroid x="335.11554" y="14.228201" model="asteroid.jme" />
	<asteroid x="377.8935" y="6.79821" model="asteroid.jme" />
	<asteroid x="154.71516" y="-11.768962" model="asteroid.jme" />
	<asteroid x="116.7204" y="13.730719" model="asteroid.jme" />
	<asteroid x="306.96558" y="10.34029" model="asteroid.jme" />
	<asteroid x="264.83072" y="5.733055" model="asteroid.jme" />
	<asteroid x="253.06334" y="13.595314" model="asteroid.jme" />
	<asteroid x="115.819214" y="5.343527" model="asteroid.jme" />
	<asteroid x="276.15527" y="-12.196317" model="asteroid.jme" />
	<asteroid x="411.67136" y="2.9925766" model="asteroid.jme" />
	<asteroid x="422.5203" y="-9.18936" model="asteroid.jme" />
	<asteroid x="409.1352" y="14.315584" model="asteroid.jme" />
	<asteroid x="432.2695" y="6.826195" model="asteroid.jme" />
	<asteroid x="577.01025" y="-12.562135" model="asteroid.jme" />
	<asteroid x="419.1926" y="-5.8532257" model="asteroid.jme" />
	<asteroid x="498.19016" y="5.7093983" model="asteroid.jme" />
	<asteroid x="477.64124" y="13.139618" model="asteroid.jme" />
	<asteroid x="485.74664" y="12.398094" model="asteroid.jme" />
	<asteroid x="621.9753" y="10.889292" model="asteroid.jme" />
	<asteroid x="617.16406" y="1.8816185" model="asteroid.jme" />
	<asteroid x="601.11127" y="5.4370174" model="asteroid.jme" />
	<asteroid x="545.0361" y="4.909073" model="asteroid.jme" />
	<asteroid x="577.0972" y="-3.9252787" model="asteroid.jme" />
	<asteroid x="656.10706" y="3.5350704" model="asteroid.jme" />
	<asteroid x="612.40204" y="14.686958" model="asteroid.jme" />
	<asteroid x="423.49283" y="8.359999" model="asteroid.jme" />
	<asteroid x="475.74133" y="6.6651382" model="asteroid.jme" />
	<asteroid x="529.23785" y="12.741493" model="asteroid.jme" />
	<asteroid x="650.77716" y="-15.550295" model="asteroid.jme" />
	<asteroid x="426.0652" y="5.6734314" model="asteroid.jme" />
	<asteroid x="615.9115" y="-3.7127962" model="asteroid.jme" />
	<asteroid x="658.25134" y="13.059975" model="asteroid.jme" />
	<asteroid x="656.65894" y="1.3203678" model="asteroid.jme" />
	<asteroid x="472.005" y="14.143448" model="asteroid.jme" />
	<asteroid x="845.59863" y="11.660671" model="asteroid.jme" />
	<asteroid x="712.963" y="-6.1239033" model="asteroid.jme" />
	<asteroid x="924.8962" y="-11.376003" model="asteroid.jme" />
	<asteroid x="831.9615" y="-0.9429827" model="asteroid.jme" />
	<asteroid x="776.8799" y="3.8413258" model="asteroid.jme" />
	<asteroid x="822.8021" y="-13.913218" model="asteroid.jme" />
	<asteroid x="777.6741" y="0.48763847" model="asteroid.jme" />
	<asteroid x="921.97235" y="-6.776429" model="asteroid.jme" />
	<asteroid x="902.6997" y="11.4033985" model="asteroid.jme" />
	<asteroid x="926.2926" y="-11.744165" model="asteroid.jme" />
	<asteroid x="895.7649" y="-10.585661" model="asteroid.jme" />
	<asteroid x="819.4147" y="-14.462226" model="asteroid.jme" />
	<asteroid x="906.31714" y="8.686413" model="asteroid.jme" />
	<asteroid x="716.8566" y="-9.634803" model="asteroid.jme" />
	<asteroid x="799.087" y="8.484104" model="asteroid.jme" />
	<asteroid x="755.80347" y="13.700508" model="asteroid.jme" />
	<asteroid x="905.053" y="0.23150444" model="asteroid.jme" />
	<asteroid x="843.25446" y="-9.713096" model="asteroid.jme" />
	<asteroid x="805.16504" y="-6.6931915" model="asteroid.jme" />
	<asteroid x="846.266" y="8.223045" model="asteroid.jme" />
	<asteroid x="818.5878" y="-9.467827" model="asteroid.jme" />
	<asteroid x="861.01575" y="2.1007385" model="asteroid.jme" />
	<asteroid x="705.3583" y="4.8520584" model="asteroid.jme" />
	<asteroid x="883.20514" y="-1.1605597" model="asteroid.jme" />
	<asteroid x="939.3015" y="10.22451" model="asteroid.jme" />
	<asteroid x="770.92255" y="-0.6174059" model="asteroid.jme" />
	<asteroid x="760.80536" y="-1.7189856" model="asteroid.jme" />
	<asteroid x="842.5021" y="-9.547888" model="asteroid.jme" />
	<asteroid x="830.63055" y="3.8418598" model="asteroid.jme" />
	<asteroid x="786.14514" y="0.5885353" model="asteroid.jme" />
	<asteroid x="925.3136" y="14.905159" model="asteroid.jme" />
	<asteroid x="775.1106" y="7.7356396" model="asteroid.jme" />
	<asteroid x="741.9208" y="0.25894547" model="asteroid.jme" />
	<asteroid x="782.13257" y="-0.34043217" model="asteroid.jme" />
	<asteroid x="764.9187" y="6.3970203" model="asteroid.jme" />
	<powerUp x="50.0" y="-14.0" model="powerup.jme" />
	<powerUp x="50.0" y="-14.0" model="powerup.jme" />
	<powerUp x="150.0" y="2.0" model="powerup.jme" />
	<powerUp x="150.0" y="2.0" model="powerup.jme" />
	<powerUp x="250.0" y="6.0" model="powerup.jme" />
	<powerUp x="250.0" y="6.0" model="powerup.jme" />
	<powerUp x="350.0" y="-14.0" model="powerup.jme" />
	<powerUp x="350.0" y="-14.0" model="powerup.jme" />
	<powerUp x="450.0" y="2.0" model="powerup.jme" />
	<powerUp x="450.0" y="2.0" model="powerup.jme" />
	<powerUp x="550.0" y="-14.0" model="powerup.jme" />
	<powerUp x="550.0" y="-14.0" model="powerup.jme" />
	<powerUp x="650.0" y="10.0" model="powerup.jme" />
	<powerUp x="650.0" y="10.0" model="powerup.jme" />
	<powerUp x="750.0" y="-14.0" model="powerup.jme" />
	<powerUp x="750.0" y="-14.0" model="powerup.jme" />
	<powerUp x="850.0" y="6.0" model="powerup.jme" />
	<powerUp x="850.0" y="6.0" model="powerup.jme" />
	<powerUp x="950.0" y="-2.0" model="powerup.jme" />
	<powerUp x="950.0" y="-2.0" model="powerup.jme" />
</race>

=== finnor-archive/base/Java/AI for Space Racer/spaceracer/races/Question2.xml
<?xml version="1.0" encoding="UTF-8"?>
<race name="Question2" width="1000" height="40" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RaceSchema.xsd">
	<asteroid x="74.85845" y="-20.0" model="asteroid.jme" />
	<asteroid x="74.85845" y="-16.0" model="asteroid.jme" />
	<asteroid x="74.85845" y="-12.0" model="asteroid.jme" />
	<asteroid x="74.85845" y="-8.0" model="asteroid.jme" />
	<asteroid x="74.85845" y="-4.0" model="asteroid.jme" />
	<asteroid x="74.85845" y="0.0" model="asteroid.jme" />
	<asteroid x="74.85845" y="4.0" model="asteroid.jme" />
	<asteroid x="189.06648" y="0.0" model="asteroid.jme" />
	<asteroid x="189.06648" y="4.0" model="asteroid.jme" />
	<asteroid x="189.06648" y="8.0" model="asteroid.jme" />
	<asteroid x="189.06648" y="12.0" model="asteroid.jme" />
	<asteroid x="189.06648" y="16.0" model="asteroid.jme" />
	<asteroid x="189.06648" y="20.0" model="asteroid.jme" />
	<asteroid x="301.36996" y="-20.0" model="asteroid.jme" />
	<asteroid x="301.36996" y="-16.0" model="asteroid.jme" />
	<asteroid x="301.36996" y="-12.0" model="asteroid.jme" />
	<asteroid x="301.36996" y="-8.0" model="asteroid.jme" />
	<asteroid x="301.36996" y="-4.0" model="asteroid.jme" />
	<asteroid x="301.36996" y="0.0" model="asteroid.jme" />
	<asteroid x="301.36996" y="4.0" model="asteroid.jme" />
	<asteroid x="417.53955" y="0.0" model="asteroid.jme" />
	<asteroid x="417.53955" y="4.0" model="asteroid.jme" />
	<asteroid x="417.53955" y="8.0" model="asteroid.jme" />
	<asteroid x="417.53955" y="12.0" model="asteroid.jme" />
	<asteroid x="417.53955" y="16.0" model="asteroid.jme" />
	<asteroid x="417.53955" y="20.0" model="asteroid.jme" />
	<asteroid x="529.38617" y="-20.0" model="asteroid.jme" />
	<asteroid x="529.38617" y="-16.0" model="asteroid.jme" />
	<asteroid x="529.38617" y="-12.0" model="asteroid.jme" />
	<asteroid x="529.38617" y="-8.0" model="asteroid.jme" />
	<asteroid x="529.38617" y="-4.0" model="asteroid.jme" />
	<asteroid x="529.38617" y="0.0" model="asteroid.jme" />
	<asteroid x="529.38617" y="4.0" model="asteroid.jme" />
	<asteroid x="643.6852" y="-4.0" model="asteroid.jme" />
	<asteroid x="643.6852" y="0.0" model="asteroid.jme" />
	<asteroid x="643.6852" y="4.0" model="asteroid.jme" />
	<asteroid x="643.6852" y="8.0" model="asteroid.jme" />
	<asteroid x="643.6852" y="12.0" model="asteroid.jme" />
	<asteroid x="643.6852" y="16.0" model="asteroid.jme" />
	<asteroid x="643.6852" y="20.0" model="asteroid.jme" />
	<asteroid x="762.77637" y="-20.0" model="asteroid.jme" />
	<asteroid x="762.77637" y="-16.0" model="asteroid.jme" />
	<asteroid x="762.77637" y="-12.0" model="asteroid.jme" />
	<asteroid x="762.77637" y="-8.0" model="asteroid.jme" />
	<asteroid x="762.77637" y="-4.0" model="asteroid.jme" />
	<asteroid x="762.77637" y="0.0" model="asteroid.jme" />
	<asteroid x="762.77637" y="4.0" model="asteroid.jme" />
	<asteroid x="886.7395" y="-4.0" model="asteroid.jme" />
	<asteroid x="886.7395" y="0.0" model="asteroid.jme" />
	<asteroid x="886.7395" y="4.0" model="asteroid.jme" />
	<asteroid x="886.7395" y="8.0" model="asteroid.jme" />
	<asteroid x="886.7395" y="12.0" model="asteroid.jme" />
	<asteroid x="886.7395" y="16.0" model="asteroid.jme" />
	<asteroid x="886.7395" y="20.0" model="asteroid.jme" />
</race>
